#!/bin/bash
# Usage: kk list-secrets

DESCRIPTION="List all secrets in .kk namespace stored in macOS Keychain."
source "$HOME/.kk/lib/common"

RESULTS=$(kk_list_secrets)

if [ -z "$RESULTS" ]; then
  echo "no secrets found."
else
  echo "$RESULTS"
fi
